monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
    handlers:
        main:
            type: stream
            path: php://stderr
            level: debug
            channels: [ "!event" ]

when@dev:
    monolog:
        handlers:
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: php://stderr
                level: debug

when@prod: &prod
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
#                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            nested:
                type: stream
                path: php://stderr
                level: debug
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr

when@stage: *prod
