when@dev:
  simple_authenticator:
    route:
      redirect_success: 'profile_edit'
      redirect_failure: 'app_login'

    security:
      firewalls:
        main:
          custom_authenticators:
            - ShieldW4ll\SimpleAuthenticator\Security\EmailAuthenticator