<?php

namespace App\Repository;

use App\Entity\Education;
use App\Entity\UserInterface;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * EducationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @method UserInterface[] findBy(array $criteria, ?array $orderBy = null, $limit = null, $offset = null)
 */
class EducationRepository extends ServiceEntityRepository implements OwnerDataRepositoryInterface
{
    use OwnerDataTrait;

    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Education::class);
    }
}
