monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: sentry
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        sentry:
            type: service
            id: Sentry\Monolog\Handler
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
