name: Build

on:
  push:
    branches:
      - master
      - 3.x
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  release:
    types:
      - created

env:
  APP_ENV: ${{ secrets.APP_ENV }}

jobs:
  build-backend:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Cache backend
        id: cache-backend
        uses: actions/cache@v3
        with:
          key: backend-$APP_ENV-${{ hashFiles('**/symfony.lock') }}-${{ hashFiles('**/composer.lock') }}
          path: |
            bin/.phpunit
            vendor
            var
          restore-keys: |
            backend-$APP_ENV-${{ hashFiles('**/symfony.lock') }}-
            backend-$APP_ENV-
            backend-

      - name: Composer
        run: composer $APP_ENV

      - run: bin/console cache:warmup

      - name: Phpunit version
        run: bin/phpunit --version

  build-frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Cache frontend
        id: cache-frontend
        uses: actions/cache@v3
        with:
          key: frontend-$APP_ENV-${{ hashFiles('**/package-lock.json') }}
          path: |
            node_modules
            public
          restore-keys: |
            frontend-$APP_ENV-
            frontend-

      - name: Npm
        run: npm run $APP_ENV

  lint_backend:
    uses: eerison/myprofile/.github/workflows/lint_backend.yml@3.x
    needs: build-backend

#  test_backend:
#    uses: eerison/myprofile/.github/workflows/test_backend.yml@3.x
#    needs:
#      - build-backend
#      - build-frontend

  deploy:
    if: startsWith(github.ref, 'refs/pull/') != true
    uses: eerison/myprofile/.github/workflows/deploy.yml@3.x
    needs:
      - lint_backend
#      - test_backend
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
