name: Build dependencies

on:
  push:
    branches:
      - master
      - 3.x
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
  APP_ENV: ${{ secrets.APP_ENV }}

jobs:
  build:
    name: Build dependencies
    runs-on: ubuntu-latest
    container:
      image: 3lever/php:8.1.8-fpm-postgresql-dev
    steps:
      - uses: actions/checkout@v3