name: Build dependencies

on:
  push:
    branches:
      - master
      - 3.x
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
  APP_ENV: ${{ secrets.APP_ENV }}

jobs:
  build-backend:
    name: Build backend
    runs-on: ubuntu-latest
    container:
      image: 3lever/php:8.1.8-fpm-postgresql-dev
    steps:
      - uses: actions/checkout@v3

      - name: Cache backend
        id: cache-backend
        uses: actions/cache@v3
        with:
          key: backend-${{ hashFiles('**/symfony.lock') }}-${{ hashFiles('**/composer.lock') }}
          path: |
            bin/.phpunit
            vendor
          restore-keys: |
            backend-${{ hashFiles('**/symfony.lock') }}-
            backend-

      - name: Composer
        run: composer $APP_ENV

      - name: Webpack
        run: yarn $APP_ENV

      - name: Phpunit version
        run: bin/phpunit --version

  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    container:
      image: 3lever/php:8.1.8-fpm-postgresql-dev
    steps:
      - uses: actions/checkout@v3

      - name: Cache frontend
        id: cache-frontend
        uses: actions/cache@v3
        with:
          key: frontend-${{ hashFiles('**/yarn.lock') }}
          path: |
            node_modules
            public
          restore-keys: |
            frontend-

      - name: Yarn
        run: yarn $APP_ENV