name: Deploy

on:
  workflow_call: ~

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: 3lever/php:8.1.8-fpm-postgresql-dev
    steps:
      - uses: actions/checkout@v3
      - uses: rlespinasse/github-slug-action@v3.x

      - uses: actions/cache@v3
        with:
          key: backend-${{ hashFiles('**/symfony.lock') }}-${{ hashFiles('**/composer.lock') }}
          path: |
            bin/.phpunit
            vendor

      - uses: actions/cache@v3
        with:
          key: frontend-${{ hashFiles('**/yarn.lock') }}
          path: |
            node_modules
            public
          restore-keys: |
            frontend-

      - name: See files
        run: |
          pwd
          ls -lha
          ls -lha vendor

      - name: Deploying
        run: ls