name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      git_ref:
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_ENV: ${{ secrets.APP_ENV }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      GIT_REF: ${{inputs.git_ref}}
    environment: ${{inputs.environment}}
    steps:
      - uses: actions/checkout@v3
      - uses: rlespinasse/github-slug-action@v3.x

      - uses: actions/cache@v3
        with:
          key: backend-$APP_ENV-${{ hashFiles('**/symfony.lock') }}-${{ hashFiles('**/composer.lock') }}
          path: |
            bin/.phpunit
            vendor
            var

      - uses: actions/cache@v3
        with:
          key: frontend-$APP_ENV-${{ hashFiles('**/package-lock.json') }}
          path: |
            node_modules
            public
          restore-keys: |
            frontend-$APP_ENV-
            frontend-

      - name: Run npm
        run: npm run ${{env.APP_ENV}}

        # TODO try to use rclone
      -   uses: actions/setup-python@v2
          with:
              python-version: '3.11'

      -   name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install awscli

      -   name: Upload assets to bucket
          run: |
            aws s3 cp public/build s3://assets --endpoint-url  ${{env.ENDPOINT_URL}} --recursive
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
            ENDPOINT_URL: https://${{secrets.CLOUDFLARE_ACCOUNT_ID}}.r2.cloudflarestorage.com/myprofile-${{env.APP_ENV}}


      - name: Serverless deploy
        uses: serverless/github-action@v3.1
        with:
          args: deploy --stage ${{env.APP_ENV}}
        env:
#              SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          # or if using AWS credentials directly
           AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
           AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
