name: Lint backend

on:
  workflow_call: ~

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
#          - 'phpstan' #It needs the database setup
          - 'ecs'
          - 'container'
          - 'rector'
          - 'twig'
          - 'translation en'
          - 'translation pt_BR'
    container:
      image: 3lever/php:8.1.8-fpm-postgresql-dev
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          key: backend-${{ hashFiles('**/symfony.lock') }}-${{ hashFiles('**/composer.lock') }}
          path: |
            bin/.phpunit
            vendor

      - name: See files
        run: |
          pwd
          ls -lha

      - name: Checking ${{ matrix.command }}
        run: composer lint:${{ matrix.command }}