name: Lint backend

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      APP_ENV: ${{ secrets.APP_ENV }}
    environment: ${{inputs.environment}}
    strategy:
      matrix:
        command:
#          - 'phpstan' #It needs the database setup
          - 'ecs'
          - 'container'
          - 'rector'
          - 'twig'
          - 'translation en'
          - 'translation pt_BR'
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - uses: actions/cache@v3
        with:
          key: backend-$APP_ENV-${{ hashFiles('**/symfony.lock') }}-${{ hashFiles('**/composer.lock') }}
          path: |
            bin/.phpunit
            vendor
            var

      - name: See files
        run: |
          pwd
          ls -lha

      - name: Checking ${{ matrix.command }}
        run: composer lint:${{ matrix.command }}
