name: Pull request - Workflow

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    uses: eerison/myprofile/.github/workflows/build.yml@master
    environment: staging_pr

  lint_backend:
    uses: eerison/myprofile/.github/workflows/lint_backend.yml@master
    needs: build

