name: Test backend

on:
  workflow_call: ~

jobs:
  test:
    name: Test backend
    runs-on: ubuntu-latest
    env:
      APP_ENV: test
      DATABASE_URL: postgres://myprofile:123456@localhost:5432/myprofile
      MAILER_DSN: null://null
      XDEBUG_MODE: coverage
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: myprofile
          POSTGRES_PASSWORD: 123456
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: See files
        run: |
          pwd
          ls -lha

      - uses: actions/cache@v3
        with:
          key: backend-$APP_ENV-${{ hashFiles('**/symfony.lock') }}-${{ hashFiles('**/composer.lock') }}
          path: |
            bin/.phpunit
            vendor

      - uses: actions/cache@v3
        with:
          key: frontend-$APP_ENV-${{ hashFiles('**/package-lock.json') }}
          path: |
            node_modules
            public
          restore-keys: |
            frontend-

      - name: Setup Database
        run: composer db

      - name: Fixtures
        run: composer db:fixtures

      - name: See files
        run: |
          pwd
          ls -lha

      - name: Run Tests
        run: composer test

      - name: Validate database schema
        run: composer db:validate

      - name: Codecov
        uses: codecov/codecov-action@v1